### PR TITLE
Add rb_funcall_with_block

### PR DESCRIPTION
**Pull request by nwtgck**
Thank you for your wonderful project! I added `rb_funcall_with_block()` bindings to `Foreign/Ruby/Bindings.hsc` to adapt to block.

### CODE REVIEW

**Comment by bartavelle** [comment]
Thanks! I just released 0.3.5 on hackage, that includes your change. I hope it worked as it returned a timeout error :/

**Comment by bartavelle** [comment]
It seems that this broke the package. Do you know for which ruby versions this function is valid?

**Comment by nwtgck** [comment]
Thank you for your reply. I use the following version in my practice of hruby.

## Ruby version

```
ruby 2.3.5p376 (2017-09-14 revision 59905) [x86_64-linux-gnu]
```

## My use

Here is my use of `c_rb_funcall_with_block`.

```rb
doMapTimes :: RubyInterpreter -> IO ()
doMapTimes ri = do
  putStrLn "====== Map with original function ======"
  let func1 :: RValue -> RValue -> IO RValue
      func1 self rbArr = do -- NOTE: self !!!
        Right rbThree <- toRuby ri (3 :: Int)
        -- call Array#*
        Right rbTimesed  <- mySafeMethodCall ri rbArr "*" [rbThree]
        return rbTimesed

  -- Register function to global
  registerGlobalFunction2 ri "times3" func1

  arrTimes3Sym          <- getSymbol "times3"
  Right arrTimes3Method <- safeMethodCall ri "Kernel" "method" [arrTimes3Sym]
  Right arrTimes3Proc   <- mySafeMethodCall ri arrTimes3Method "to_proc" []

  Right rbArr  <- toRuby ri ([1, 2, 3] :: [Int])
  Right mapRID  <- makeSafe ri $ rb_intern "map"

  rbMapped <- c_rb_funcall_with_block rbArr mapRID 0 nullPtr arrTimes3Proc

  Right rbMappedInspect <- mySafeMethodCall ri rbMapped "inspect" []


  Right mappedInspect<- fromRuby ri rbMappedInspect :: IO (Either RubyError ByteString)
  print mappedInspect

  Right mapped <- fromRuby ri rbMapped :: IO (Either RubyError [Int])
  print mapped
  return ()
```

Permalink: https://github.com/nwtgck/hruby-prac-haskell/blob/a34c45a52d9252704d874519c7c3e992dfc4009a/app/Main.hs#L130


And the output is the following.

```
====== Map with original function ======
"[3, 6, 9]"
[3,6,9]
```

### Corresponding Ruby code

```rb
def times3(a)
  a * 3
end

res = [1, 2, 3].map(&method(:times3).to_proc)
p res.inspect
p res
```

I hope that it was helpfull.

**Comment by nwtgck** [comment]
## About the timeout error

When I used this, It freezed.
```hs
Right rbMapped <- makeSafe ri $ c_rb_funcall_with_block rbArr mapRID 0 nullPtr arrTimes3Proc
```

But the following works.

```rb
rbMapped <- c_rb_funcall_with_block rbArr mapRID 0 nullPtr arrTimes3Proc
```

I don't understand well about `makeSafe`.

**Comment by bartavelle** [comment]
You must use `makeSafe`! The ruby interpreter is actually not designed to be embedded, and must run in the main thread. If you don't, your code will randomly break in multi-threaded situations.

`makeSafe` makes sure it does, but it comes with a huge limitation : if in ruby you call something that must round-trip through Haskell land, you will stall.

**Comment by bartavelle** [comment]
Do you mind looking in previous ruby version to see when this function appeared so that I can place a CPP macro to guard it?

**Comment by nwtgck** [comment]
> Do you mind looking in previous ruby version to see when this function appeared so that I can place a CPP macro to guard it?

I looked at `ruby.h` in GitHub. Here is the list for `VALUE rb_funcall_with_block(VALUE, ID, int, const VALUE*, VALUE);
 `

* 2.4: https://github.com/ruby/ruby/blob/86bfcc2da07d524845fbfb3a458a84cc8bd3ecf1/include/ruby/ruby.h#L1773
* 2.3: https://github.com/ruby/ruby/blob/d69b1e3b305a79659f4686f3cffc5c03c18ea832/include/ruby/ruby.h#L1757
* 2.2: https://github.com/ruby/ruby/blob/d629ce0baa47ce800a26b451215dbeb20b3fb05c/include/ruby/ruby.h#L1499
* 2.1: https://github.com/ruby/ruby/blob/6d728bdae9de565ad9d0b2fee2d4c2a33c6f4eac/include/ruby/ruby.h#L1467
* 2.0: https://github.com/ruby/ruby/blob/073cc5e815fcf5178fe4e515fcde74dc3597adeb/include/ruby/ruby.h#L1347
* 1.9.3: https://github.com/ruby/ruby/blob/23ccbdf52188b78427f41d75b1a4b81959ac9876/include/ruby/ruby.h#L1156
* 1.9.2: NOT FOUND

So >= 1.9.2 is OK

**Comment by bartavelle** [comment]
Thanks!

**Comment by bartavelle** [comment]
I did protect it with an `#ifdef RUBY2`. This rules out 1.9.3, but hopefully this is not too troublesome.

**Pull request merged**
